version: '3.8'

services:
  app:
    build: .
    container_name: gestao-acolhidos
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=Gestao-Acolhidos
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:gestao-acolhidos}
      - SPRING_DATASOURCE_USERNAME=${USER:myuser}
      - SPRING_DATASOURCE_PASSWORD=${PASS:mypassword}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=5
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10
      - SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=30000
      - SPRING_DATASOURCE_HIKARI_POOL_NAME=SpringBootJPAHikariCP
      - SPRING_DATASOURCE_HIKARI_MAX_LIFETIME=1000000
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000
      - SPRING_DATASOURCE_HIKARI_LEAK_DETECTION_THRESHOLD=15000
      - API_PRIVATE_KEY=${JWT_KEY}
      - API_ISSUER_NAME=org.felipe.gestao-acolhidos