version: '3.8'        corsConfiguration.setAllowedOriginPatterns(List.of("https://*.railway.app"));

services:
  app:
    build: .
    container_name: gestao-acolhidos
    ports:
      - "8080:8080"
    env_file:
      - .env